// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebChat.Dati;

#nullable disable

namespace WebChat.Migrations
{
    [DbContext(typeof(BancaDati))]
    [Migration("20250528105052_Seconda")]
    partial class Seconda
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("WebChat.Dati.Strutture.Messaggio", b =>
                {
                    b.Property<uint>("IDmessaggio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contenuto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint?>("DestinatarioIDutente")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Invio")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("MittenteIDutente")
                        .HasColumnType("INTEGER");

                    b.HasKey("IDmessaggio");

                    b.HasIndex("DestinatarioIDutente");

                    b.HasIndex("MittenteIDutente");

                    b.ToTable("Messaggi");
                });

            modelBuilder.Entity("WebChat.Dati.Strutture.Utente", b =>
                {
                    b.Property<uint>("IDutente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDutente");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("WebChat.Dati.Strutture.Messaggio", b =>
                {
                    b.HasOne("WebChat.Dati.Strutture.Utente", "Destinatario")
                        .WithMany()
                        .HasForeignKey("DestinatarioIDutente")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebChat.Dati.Strutture.Utente", "Mittente")
                        .WithMany()
                        .HasForeignKey("MittenteIDutente")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Destinatario");

                    b.Navigation("Mittente");
                });
#pragma warning restore 612, 618
        }
    }
}
