// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebChat.Dati;

#nullable disable

namespace WebChat.Migrations
{
    [DbContext(typeof(BancaDati))]
    partial class BancaDatiModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("WebChat.Dati.Strutture.Gruppo", b =>
                {
                    b.Property<int>("IDgruppo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Creazione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDgruppo");

                    b.ToTable("Gruppi");
                });

            modelBuilder.Entity("WebChat.Dati.Strutture.Messaggio", b =>
                {
                    b.Property<uint>("IDmessaggio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contenuto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint?>("DestinatarioIDutente")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GruppoIDgruppo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Invio")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("MittenteIDutente")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("UtenteIDutente")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("UtenteIDutente1")
                        .HasColumnType("INTEGER");

                    b.HasKey("IDmessaggio");

                    b.HasIndex("DestinatarioIDutente");

                    b.HasIndex("GruppoIDgruppo");

                    b.HasIndex("MittenteIDutente");

                    b.HasIndex("UtenteIDutente");

                    b.HasIndex("UtenteIDutente1");

                    b.ToTable("Messaggi");
                });

            modelBuilder.Entity("WebChat.Dati.Strutture.Utente", b =>
                {
                    b.Property<uint>("IDutente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GruppoIDgruppo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDutente");

                    b.HasIndex("GruppoIDgruppo");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("WebChat.Dati.Strutture.Messaggio", b =>
                {
                    b.HasOne("WebChat.Dati.Strutture.Utente", "Destinatario")
                        .WithMany()
                        .HasForeignKey("DestinatarioIDutente")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebChat.Dati.Strutture.Gruppo", null)
                        .WithMany("Messaggi")
                        .HasForeignKey("GruppoIDgruppo");

                    b.HasOne("WebChat.Dati.Strutture.Utente", "Mittente")
                        .WithMany()
                        .HasForeignKey("MittenteIDutente")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebChat.Dati.Strutture.Utente", null)
                        .WithMany("Inviati")
                        .HasForeignKey("UtenteIDutente");

                    b.HasOne("WebChat.Dati.Strutture.Utente", null)
                        .WithMany("Ricevuti")
                        .HasForeignKey("UtenteIDutente1");

                    b.Navigation("Destinatario");

                    b.Navigation("Mittente");
                });

            modelBuilder.Entity("WebChat.Dati.Strutture.Utente", b =>
                {
                    b.HasOne("WebChat.Dati.Strutture.Gruppo", null)
                        .WithMany("Membri")
                        .HasForeignKey("GruppoIDgruppo");
                });

            modelBuilder.Entity("WebChat.Dati.Strutture.Gruppo", b =>
                {
                    b.Navigation("Membri");

                    b.Navigation("Messaggi");
                });

            modelBuilder.Entity("WebChat.Dati.Strutture.Utente", b =>
                {
                    b.Navigation("Inviati");

                    b.Navigation("Ricevuti");
                });
#pragma warning restore 612, 618
        }
    }
}
