// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stradario;

#nullable disable

namespace Stradario.Migrations
{
    [DbContext(typeof(BancaDati))]
    [Migration("20250526153908_ultimaMigrazione")]
    partial class ultimaMigrazione
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Stradario.Strutture.Arco", b =>
                {
                    b.Property<uint>("IDarco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("A")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("B")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Creazione")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Distanza")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UltimaModifica")
                        .HasColumnType("TEXT");

                    b.HasKey("IDarco");

                    b.ToTable("archi");
                });

            modelBuilder.Entity("Stradario.Strutture.Nodo", b =>
                {
                    b.Property<uint>("IDnodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Creazione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaModifica")
                        .HasColumnType("TEXT");

                    b.Property<float>("X")
                        .HasColumnType("REAL");

                    b.Property<float>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("IDnodo");

                    b.ToTable("Nodi");
                });

            modelBuilder.Entity("Stradario.Strutture.Strada", b =>
                {
                    b.Property<uint>("IDstrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AIDnodo")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("BIDnodo")
                        .HasColumnType("INTEGER");

                    b.HasKey("IDstrada");

                    b.HasIndex("AIDnodo");

                    b.HasIndex("BIDnodo");

                    b.ToTable("Strade");
                });

            modelBuilder.Entity("Stradario.Strutture.Strada", b =>
                {
                    b.HasOne("Stradario.Strutture.Nodo", "A")
                        .WithMany()
                        .HasForeignKey("AIDnodo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stradario.Strutture.Nodo", "B")
                        .WithMany()
                        .HasForeignKey("BIDnodo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("A");

                    b.Navigation("B");
                });
#pragma warning restore 612, 618
        }
    }
}
